/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ee_ut_cs_mc_natpeer_jni_NativeLibrary */

#ifndef _Included_ee_ut_cs_mc_natpeer_jni_NativeLibrary
#define _Included_ee_ut_cs_mc_natpeer_jni_NativeLibrary
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ee_ut_cs_mc_natpeer_jni_NativeLibrary
 * Method:    injectFrom
 * Signature: (Ljava/lang/String;ILjava/lang/String;Ljava/lang/String;IJJZ)V
 */
JNIEXPORT void JNICALL Java_ee_ut_cs_mc_natpeer_jni_NativeLibrary_injectFrom
  (JNIEnv *, jclass, jstring, jint, jstring, jstring, jint, jlong, jlong, jboolean);

#ifdef __cplusplus
}
#endif
#endif
